import type { NextPage } from "next";
import Head from "next/head";
import styles from "styles/Home.module.css";
import { Container, Typography, Grid, Box, Button } from "@mui/material";
import { useDateNav } from "~/hooks/useDateNav";
import { useAuthCtx } from "~/contexts/AuthCtx";
import NextLink from "next/link";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const { goToToday } = useDateNav();
  const { push } = useRouter();
  const { user_id } = useAuthCtx();
  if (!!user_id) push("/profile");
  return (
    <div className={styles.container}>
      <Head>
        <title>Gratitude Journal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box
        component="main"
        sx={{
          height: "calc(100vh - 100px)",
          display: "flex",
          flexDirection: "column",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Typography variant="h2">Gratitude Journal</Typography>
        <Typography variant="h5" color="GrayText">
          <NextLink href="/auth/signup">
            <Button variant="outlined" sx={{ mr: 1 }}>
              Sign up
            </Button>
          </NextLink>
          to create your own.
        </Typography>
        <Typography variant="subtitle2" color="GrayText">
          or{" "}
          <NextLink href="/auth/signin">
            <Button size="small" variant="outlined" sx={{ ml: 1 }}>
              Sign in
            </Button>
          </NextLink>
        </Typography>
      </Box>
    </div>
  );
};

export default Home;
